services:
  - type: web
    name: house-price-api-v1
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9